#!/bin/bash
echo Haciendo drop a la vieja DB…
rake db:drop
echo Creando una nueva DB…
rake db:create
echo Haciendo las migraciones…
rake db:migrate
echo Sembrando datos iniciales…
rake db:seed
rake db:seed:martin
echo Inicialización de bases terminada.
echo Se puede ejecutar “rails server”.
